# Generated by Django 5.2.10 on 2026-01-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GymBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Gym Branches',
                'db_table': 'gym_branches',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='gym_branche_name_b6b02b_idx'), models.Index(fields=['is_active'], name='gym_branche_is_acti_0d750f_idx')],
            },
        ),
    ]
