# Generated by Django 5.2.10 on 2026-01-14 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gyms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'TRAINER'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_workout_plans', to=settings.AUTH_USER_MODEL)),
                ('gym_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to='gyms.gymbranch')),
            ],
            options={
                'db_table': 'workout_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('due_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(limit_choices_to={'role': 'MEMBER'}, on_delete=django.db.models.deletion.CASCADE, related_name='workout_tasks', to=settings.AUTH_USER_MODEL)),
                ('workout_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workouts.workoutplan')),
            ],
            options={
                'db_table': 'workout_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workoutplan',
            index=models.Index(fields=['gym_branch', 'is_active'], name='workout_pla_gym_bra_84bd09_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutplan',
            index=models.Index(fields=['created_by'], name='workout_pla_created_0581a3_idx'),
        ),
        migrations.AddIndex(
            model_name='workouttask',
            index=models.Index(fields=['member', 'status'], name='workout_tas_member__a4b73a_idx'),
        ),
        migrations.AddIndex(
            model_name='workouttask',
            index=models.Index(fields=['workout_plan'], name='workout_tas_workout_ce8cdf_idx'),
        ),
        migrations.AddIndex(
            model_name='workouttask',
            index=models.Index(fields=['due_date'], name='workout_tas_due_dat_69cedc_idx'),
        ),
        migrations.AddIndex(
            model_name='workouttask',
            index=models.Index(fields=['status'], name='workout_tas_status_9639cd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workouttask',
            unique_together={('workout_plan', 'member', 'due_date')},
        ),
    ]
